### ISSUE TITLE
Use “new-style” classes

### ISSUE THREAD

**Issue by Zearin** [cucumber/gherkin-python#1]
_**Aside:** I have been waiting for an officially blessed Python parser for Gherkin for a long time.  Thank you for this!_

----

If a class has no other parents, it should explicitly inherit from `object`.

For Python 2.x, this changes the way that the Python runtime creates the class, and the runtime is optimized for new-style classes.  

It probably won’t make any noticeable difference—or, for really big test suites, it might.  I don’t know.  

In either case, it is considered good practice.

**Comment by aslakhellesoy** [comment]
Why don't you send us a PR to improve this? See [CONTRIBUTING.md](https://github.com/cucumber/gherkin-python/blob/master/CONTRIBUTING.md) for details.

**Comment by Zearin** [comment]
Thanks!  I will be happy to :)

(In the past, on similar issues I’ve opened a PR without asking first, and been rejected.  It sucks after putting in the effort to get rejected because some people are much more nitpicky about code style than others.  It takes all kinds of people, I suppose…  Anyway, that’s the only reason I didn’t open a PR to start with.  Look for one shortly!)

**Comment by Zearin** [comment]
@aslakhellesoy Nearly finished, but there’s no documentation on how to regenerate `parser.py` from the `gherkin-parser.razor` file.  

Currently, the tests pass for me.  But I need to regenerate the `parser.py` file to make sure it passes, too…

**Comment by Zearin** [comment]
As per `CONTRIBUTING.md`, I opened a Pull Request for this in cucumber/gherkin3/#72
